console.log(10 + "20");
console.log(9 - "5");
console.log("Java" + "Script");
console.log(" " + " ");
console.log(" " + 0);
console.log("vinod" - "thapa");
console.log(true + true);
console.log(true + false);
console.log(false + true);
console.log(false - true);